# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_yamltube.youtube as __youtube
    youtube = __youtube
else:
    youtube = _utilities.lazy_import('pulumi_yamltube.youtube')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "yamltube",
  "mod": "youtube",
  "fqn": "pulumi_yamltube.youtube",
  "classes": {
   "yamltube:youtube:Playlist": "Playlist"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "yamltube",
  "token": "pulumi:providers:yamltube",
  "fqn": "pulumi_yamltube",
  "class": "Provider"
 }
]
"""
)
