// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Yamltube.Youtube
{
    [YamltubeResourceType("yamltube:youtube:Playlist")]
    public partial class Playlist : Pulumi.CustomResource
    {
        /// <summary>
        /// the id of the channel. https://www.youtube.com/channel/&lt;channelId&gt;
        /// </summary>
        [Output("channelId")]
        public Output<string> ChannelId { get; private set; } = null!;

        /// <summary>
        /// description of the playlist
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        [Output("playlistId")]
        public Output<string> PlaylistId { get; private set; } = null!;

        /// <summary>
        /// title of the playlist
        /// </summary>
        [Output("title")]
        public Output<string> Title { get; private set; } = null!;

        /// <summary>
        /// array of youtube links or ids. (https://www.youtube.com/watch?v=dQw4w9WgXcQ, or dQw4w9WgXcQ)
        /// </summary>
        [Output("videos")]
        public Output<ImmutableArray<string>> Videos { get; private set; } = null!;

        /// <summary>
        /// visibility of the playlist. valid values are public, private, unlisted
        /// </summary>
        [Output("visibility")]
        public Output<string> Visibility { get; private set; } = null!;


        /// <summary>
        /// Create a Playlist resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Playlist(string name, PlaylistArgs args, CustomResourceOptions? options = null)
            : base("yamltube:youtube:Playlist", name, args ?? new PlaylistArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Playlist(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("yamltube:youtube:Playlist", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Playlist resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Playlist Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Playlist(name, id, options);
        }
    }

    public sealed class PlaylistArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// the id of the channel. https://www.youtube.com/channel/&lt;channelId&gt;
        /// </summary>
        [Input("channelId")]
        public Input<string>? ChannelId { get; set; }

        /// <summary>
        /// description of the playlist
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        [Input("playlistId")]
        public Input<string>? PlaylistId { get; set; }

        /// <summary>
        /// title of the playlist
        /// </summary>
        [Input("title", required: true)]
        public Input<string> Title { get; set; } = null!;

        [Input("videos", required: true)]
        private InputList<string>? _videos;

        /// <summary>
        /// array of youtube links or ids. (https://www.youtube.com/watch?v=dQw4w9WgXcQ, or dQw4w9WgXcQ)
        /// </summary>
        public InputList<string> Videos
        {
            get => _videos ?? (_videos = new InputList<string>());
            set => _videos = value;
        }

        /// <summary>
        /// visibility of the playlist. valid values are public, private, unlisted
        /// </summary>
        [Input("visibility", required: true)]
        public Input<string> Visibility { get; set; } = null!;

        public PlaylistArgs()
        {
        }
    }
}
