// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Playlist extends pulumi.CustomResource {
    /**
     * Get an existing Playlist resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Playlist {
        return new Playlist(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'yamltube:youtube:Playlist';

    /**
     * Returns true if the given object is an instance of Playlist.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Playlist {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Playlist.__pulumiType;
    }

    /**
     * the id of the channel. https://www.youtube.com/channel/<channelId>
     */
    public readonly channelId!: pulumi.Output<string>;
    /**
     * description of the playlist
     */
    public readonly description!: pulumi.Output<string>;
    public readonly playlistId!: pulumi.Output<string>;
    /**
     * title of the playlist
     */
    public readonly title!: pulumi.Output<string>;
    /**
     * array of youtube links or ids. (https://www.youtube.com/watch?v=dQw4w9WgXcQ, or dQw4w9WgXcQ)
     */
    public readonly videos!: pulumi.Output<string[]>;
    /**
     * visibility of the playlist. valid values are public, private, unlisted
     */
    public readonly visibility!: pulumi.Output<string>;

    /**
     * Create a Playlist resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PlaylistArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.description === undefined) && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            if ((!args || args.title === undefined) && !opts.urn) {
                throw new Error("Missing required property 'title'");
            }
            if ((!args || args.videos === undefined) && !opts.urn) {
                throw new Error("Missing required property 'videos'");
            }
            if ((!args || args.visibility === undefined) && !opts.urn) {
                throw new Error("Missing required property 'visibility'");
            }
            resourceInputs["channelId"] = args ? args.channelId : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["playlistId"] = args ? args.playlistId : undefined;
            resourceInputs["title"] = args ? args.title : undefined;
            resourceInputs["videos"] = args ? args.videos : undefined;
            resourceInputs["visibility"] = args ? args.visibility : undefined;
        } else {
            resourceInputs["channelId"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["playlistId"] = undefined /*out*/;
            resourceInputs["title"] = undefined /*out*/;
            resourceInputs["videos"] = undefined /*out*/;
            resourceInputs["visibility"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Playlist.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Playlist resource.
 */
export interface PlaylistArgs {
    /**
     * the id of the channel. https://www.youtube.com/channel/<channelId>
     */
    channelId?: pulumi.Input<string>;
    /**
     * description of the playlist
     */
    description: pulumi.Input<string>;
    playlistId?: pulumi.Input<string>;
    /**
     * title of the playlist
     */
    title: pulumi.Input<string>;
    /**
     * array of youtube links or ids. (https://www.youtube.com/watch?v=dQw4w9WgXcQ, or dQw4w9WgXcQ)
     */
    videos: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * visibility of the playlist. valid values are public, private, unlisted
     */
    visibility: pulumi.Input<string>;
}
